repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.1
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
  - repo: local
    hooks:
      - id: tests
        name: run tests
        verbose: true
        language: system
        stages: [ commit ]
        entry: pytest --cov-config=pyproject.toml --cov=. --cov-report=json --cov-report=term-missing
        require_serial: true
        always_run: true
        pass_filenames: false
      - id: coverage
        name: check coverage
        verbose: true
        language: system
        stages: [ commit ]
        entry: python pre-commit.py coverage --expected-coverage 65 coverage.json
        require_serial: true
        always_run: true
        pass_filenames: false
      - id: check-updates
        name: check updates for dependencies
        verbose: true
        language: system
        stages: [ commit ]
        entry: python pre-commit.py check-updates
        require_serial: true
        always_run: true
        pass_filenames: false
