repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.4
    hooks:
      - id: ruff
      - id: ruff-format
#  temporary comment and using local mypy hook
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.11.0
#    hooks:
#      - id: mypy
  - repo: local
    hooks:
      - id: mypy
        name: mypy check
        verbose: true
        language: system
        stages: [ commit ]
        entry: mypy .
        require_serial: true
        always_run: true
        pass_filenames: false
      - id: tests
        name: run tests
        verbose: true
        language: system
        stages: [ commit ]
        entry: pytest --cov-config=pyproject.toml --cov=. --cov-report=json --cov-report=term-missing
        require_serial: true
        always_run: true
        pass_filenames: false
      - id: coverage
        name: check coverage
        verbose: true
        language: system
        stages: [ commit ]
        entry: python pre-commit.py coverage --expected-coverage 80 coverage.json
        require_serial: true
        always_run: true
        pass_filenames: false
      - id: check-updates
        name: check updates for dependencies
        verbose: true
        language: system
        stages: [ commit ]
        entry: python pre-commit.py check-updates
        require_serial: true
        always_run: true
        pass_filenames: false
