repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
  - repo: local
    hooks:
      - id: check-updates
        name: check updates for dependencies
        verbose: true
        language: system
        stages: [ commit ]
        entry: python pre-commit.py check-updates
        require_serial: true
        always_run: true
        pass_filenames: false
