[project]
name = "DBDPlanner"
version = "2.0"
requires-python = ">=3.12"
dependencies = [
    "pip==24.0",
    "setuptools==69.5.1",
    "wheel==0.43.0",

    "numpy==1.26.4",
    "Pillow==10.3.0",
]

[project.optional-dependencies]
installer = ["uv==0.1.39"]
tests = ["click==8.1.7"]
