from enum import Enum, IntEnum, StrEnum


class Grade(IntEnum):
    """Enum of grades."""

    ASH = 1
    BRONZE = 2
    SILVER = 3
    GOLD = 4
    IRIDESCENT = 5


class WeekdayShort(Enum):
    """Enum of weekdays, limited 3 letters."""

    MONDAY = 'Mon'
    TUESDAY = 'Tue'
    WEDNESDAY = 'Wed'
    THURSDAY = 'Thu'
    FRIDAY = 'Fri'
    SATURDAY = 'Sat'
    SUNDAY = 'Sun'


class StrColor(StrEnum):
    """Enum of string color, used in Pillow.

    Reference: colormap PIL/ImageColor.py:165 (Pillow==10.3.0)
    """

    ALICEBLUE = 'aliceblue'
    ANTIQUEWHITE = 'antiquewhite'
    AQUA = 'aqua'
    AQUAMARINE = 'aquamarine'
    AZURE = 'azure'
    BEIGE = 'beige'
    BISQUE = 'bisque'
    BLACK = 'black'
    BLANCHEDALMOND = 'blanchedalmond'
    BLUE = 'blue'
    BLUEVIOLET = 'blueviolet'
    BROWN = 'brown'
    BURLYWOOD = 'burlywood'
    CADETBLUE = 'cadetblue'
    CHARTREUSE = 'chartreuse'
    CHOCOLATE = 'chocolate'
    CORAL = 'coral'
    CORNFLOWERBLUE = 'cornflowerblue'
    CORNSILK = 'cornsilk'
    CRIMSON = 'crimson'
    CYAN = 'cyan'
    DARKBLUE = 'darkblue'
    DARKCYAN = 'darkcyan'
    DARKGOLDENROD = 'darkgoldenrod'
    DARKGRAY = 'darkgray'
    DARKGREY = 'darkgrey'
    DARKGREEN = 'darkgreen'
    DARKKHAKI = 'darkkhaki'
    DARKMAGENTA = 'darkmagenta'
    DARKOLIVEGREEN = 'darkolivegreen'
    DARKORANGE = 'darkorange'
    DARKORCHID = 'darkorchid'
    DARKRED = 'darkred'
    DARKSALMON = 'darksalmon'
    DARKSEAGREEN = 'darkseagreen'
    DARKSLATEBLUE = 'darkslateblue'
    DARKSLATEGRAY = 'darkslategray'
    DARKSLATEGREY = 'darkslategrey'
    DARKTURQUOISE = 'darkturquoise'
    DARKVIOLET = 'darkviolet'
    DEEPPINK = 'deeppink'
    DEEPSKYBLUE = 'deepskyblue'
    DIMGRAY = 'dimgray'
    DIMGREY = 'dimgrey'
    DODGERBLUE = 'dodgerblue'
    FIREBRICK = 'firebrick'
    FLORALWHITE = 'floralwhite'
    FORESTGREEN = 'forestgreen'
    FUCHSIA = 'fuchsia'
    GAINSBORO = 'gainsboro'
    GHOSTWHITE = 'ghostwhite'
    GOLD = 'gold'
    GOLDENROD = 'goldenrod'
    GRAY = 'gray'
    GREY = 'grey'
    GREEN = 'green'
    GREENYELLOW = 'greenyellow'
    HONEYDEW = 'honeydew'
    HOTPINK = 'hotpink'
    INDIANRED = 'indianred'
    INDIGO = 'indigo'
    IVORY = 'ivory'
    KHAKI = 'khaki'
    LAVENDER = 'lavender'
    LAVENDERBLUSH = 'lavenderblush'
    LAWNGREEN = 'lawngreen'
    LEMONCHIFFON = 'lemonchiffon'
    LIGHTBLUE = 'lightblue'
    LIGHTCORAL = 'lightcoral'
    LIGHTCYAN = 'lightcyan'
    LIGHTGOLDENRODYELLOW = 'lightgoldenrodyellow'
    LIGHTGREEN = 'lightgreen'
    LIGHTGRAY = 'lightgray'
    LIGHTGREY = 'lightgrey'
    LIGHTPINK = 'lightpink'
    LIGHTSALMON = 'lightsalmon'
    LIGHTSEAGREEN = 'lightseagreen'
    LIGHTSKYBLUE = 'lightskyblue'
    LIGHTSLATEGRAY = 'lightslategray'
    LIGHTSLATEGREY = 'lightslategrey'
    LIGHTSTEELBLUE = 'lightsteelblue'
    LIGHTYELLOW = 'lightyellow'
    LIME = 'lime'
    LIMEGREEN = 'limegreen'
    LINEN = 'linen'
    MAGENTA = 'magenta'
    MAROON = 'maroon'
    MEDIUMAQUAMARINE = 'mediumaquamarine'
    MEDIUMBLUE = 'mediumblue'
    MEDIUMORCHID = 'mediumorchid'
    MEDIUMPURPLE = 'mediumpurple'
    MEDIUMSEAGREEN = 'mediumseagreen'
    MEDIUMSLATEBLUE = 'mediumslateblue'
    MEDIUMSPRINGGREEN = 'mediumspringgreen'
    MEDIUMTURQUOISE = 'mediumturquoise'
    MEDIUMVIOLETRED = 'mediumvioletred'
    MIDNIGHTBLUE = 'midnightblue'
    MINTCREAM = 'mintcream'
    MISTYROSE = 'mistyrose'
    MOCCASIN = 'moccasin'
    NAVAJOWHITE = 'navajowhite'
    NAVY = 'navy'
    OLDLACE = 'oldlace'
    OLIVE = 'olive'
    OLIVEDRAB = 'olivedrab'
    ORANGE = 'orange'
    ORANGERED = 'orangered'
    ORCHID = 'orchid'
    PALEGOLDENROD = 'palegoldenrod'
    PALEGREEN = 'palegreen'
    PALETURQUOISE = 'paleturquoise'
    PALEVIOLETRED = 'palevioletred'
    PAPAYAWHIP = 'papayawhip'
    PEACHPUFF = 'peachpuff'
    PERU = 'peru'
    PINK = 'pink'
    PLUM = 'plum'
    POWDERBLUE = 'powderblue'
    PURPLE = 'purple'
    REBECCAPURPLE = 'rebeccapurple'
    RED = 'red'
    ROSYBROWN = 'rosybrown'
    ROYALBLUE = 'royalblue'
    SADDLEBROWN = 'saddlebrown'
    SALMON = 'salmon'
    SANDYBROWN = 'sandybrown'
    SEAGREEN = 'seagreen'
    SEASHELL = 'seashell'
    SIENNA = 'sienna'
    SILVER = 'silver'
    SKYBLUE = 'skyblue'
    SLATEBLUE = 'slateblue'
    SLATEGRAY = 'slategray'
    SLATEGREY = 'slategrey'
    SNOW = 'snow'
    SPRINGGREEN = 'springgreen'
    STEELBLUE = 'steelblue'
    TAN = 'tan'
    TEAL = 'teal'
    THISTLE = 'thistle'
    TOMATO = 'tomato'
    TURQUOISE = 'turquoise'
    VIOLET = 'violet'
    WHEAT = 'wheat'
    WHITE = 'white'
    WHITESMOKE = 'whitesmoke'
    YELLOW = 'yellow'
    YELLOWGREEN = 'yellowgreen'
