name: Code checking
on: [push]
jobs:
  linters:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv==0.2.5
        uv pip install --extra dev_tools -r pyproject.toml  --system
    - name: Checking with ruff linter
      run: |
        ruff check $(git ls-files '*.py')
    - name: Checking with ruff formatter
      run: |
        ruff format $(git ls-files '*.py') --check
    - name: Checking with mypy type checker
      run: |
        mypy $(git ls-files '*.py')
    - name: Checking updates of packages
      run: |
        ./.github/workflows/check_updates.sh
      continue-on-error: true
  install_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run install script
        run: ./install_windows.bat
        shell: cmd
      - name: Run project
        run: | 
          ./.venv\Scripts\activate.bat
          python create_plan.py
        shell: cmd
  install_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run install script
        run: ./install_linux_and_macos.sh
        shell: bash
      - name: Run project
        run: |
          source .venv/bin/activate
          python create_plan.py
  install_macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run install script
        run: ./install_linux_and_macos.sh
        shell: sh
      - name: Run project
        run: |
          source .venv/bin/activate
          python create_plan.py
