name: Code checking
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv==0.2.5
        uv pip install --extra dev_tools -r pyproject.toml
    - name: Checking with ruff linter
      run: |
        ruff check $(git ls-files '*.py')
    - name: Checking with ruff formatter
      run: |
        ruff format $(git ls-files '*.py') --check
    - name: Checking with mypy type checker
      run: |
        mypy $(git ls-files '*.py')
