name: 'coverage'
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip install --all-extras -r pyproject.toml --system
      - name: Run auto tests
        run: pytest --cov-config=pyproject.toml --cov=. --cov-report=json --cov-report=term-missing --cov-report=xml
      - name: Code coverage
        uses: orgoro/coverage@v3.1
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}