name: Installing on different platforms
on: [push]
jobs:
  install-windows-3_12:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run install script
        run: ./install_windows.bat
        shell: cmd
      - name: Run project
        run: .venv\Scripts\activate.bat && python create_plan.py
        shell: cmd
  install-linux-3_12:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run install script
        run: ./install_linux_and_macos.sh
        shell: bash
      - name: Run project
        run: |
          source .venv/bin/activate
          python create_plan.py
  install-macos-3_12:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run install script
        run: ./install_linux_and_macos.sh
        shell: sh
      - name: Run project
        run: |
          source .venv/bin/activate
          python create_plan.py
  install-windows-3_13:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ "3.13" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run install script
        run: ./install_windows.bat
        shell: cmd
      - name: Run project
        run: .venv\Scripts\activate.bat && python create_plan.py
        shell: cmd
  install-linux-3_13:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.13" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run install script
        run: ./install_linux_and_macos.sh
        shell: bash
      - name: Run project
        run: |
          source .venv/bin/activate
          python create_plan.py
  install-macos-3_13:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [ "3.13" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run install script
        run: ./install_linux_and_macos.sh
        shell: sh
      - name: Run project
        run: |
          source .venv/bin/activate
          python create_plan.py